backend:
  name: github
  repo: alifiratuzun/abakus
  branch: main
  site_domain: abakus-studio.netlify.app
  base_url: https://github.com
  auth_endpoint: https://github.com/login/oauth/authorize
  client_id: Ov23liUpWD4ZiILCk0MP


media_folder: "img"
public_folder: "/img"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Architect", name: "architect", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Images", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"} }
      - { label: "Plans", name: "plans", widget: "list", field: {label: "Plan", name: "plan", widget: "image"} }
      - { label: "Layout", name: "layout", widget: "hidden", default: "project.njk" }
