backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

local_backend: false

# Disable identity widget to prevent conflicts
identity:
  widget: false

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "project.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Type", name: "type", widget: "select", options: ["house", "cultural", "commercial"] }
      - { label: "Images", name: "images", widget: "list", required: false, field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Description", name: "body", widget: "text" }
