backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

local_backend: false

# Disable identity widget to prevent conflicts
identity:
  widget: false

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Ne (Tip)", name: "what", widget: "string", required: true, hint: "e.g. Konut" }
      - { label: "Kim (Mimar)", name: "who", widget: "string", required: true, hint: "e.g. Mimar Sinan" }
      - { label: "Nerede (Yer)", name: "where", widget: "string", required: true, hint: "e.g. Istanbul" }
      - { label: "Ne Zaman (Tarih)", name: "when", widget: "string", required: true, hint: "e.g. 1997" }
      - label: "Images"
        name: "images"
        widget: "list"
        required: true
        default:
          - image: "/img/placeholder.jpg"
            alt: "Placeholder image"
        fields:
          - { label: "Image", name: "image", widget: "image", required: true }
          - { label: "Alt Text", name: "alt", widget: "string", required: false, hint: "Describe the image for accessibility" }
      - { label: "Order", name: "order", widget: "number", required: false, hint: "Set this to control project order (lower = first)" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Footnote", name: "footnote", widget: "markdown", required: false, hint: "Add sources or credits for images/texts. This will appear as a small footnote at the bottom of the project page." }
      - { label: "Layout", name: "layout", widget: "hidden", default: "project.njk" }
