backend:
  name: github
  repo: alifiratuzun/abakus
  branch: main
  client_id: Ov23lihHZUZkzBaIPcNr
  auth_type: pkce

media_folder: "img"
public_folder: "/img"

local_backend: false

# Disable identity widget to prevent conflicts
identity:
  widget: false

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["house", "cultural", "commercial"] }
      - { label: "Description", name: "body", widget: "text" }
      - { label: "Images", name: "images", widget: "list", required: false,
          field: { label: "Image", name: "image", widget: "image" }
        }
