backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

local_backend: false

# Disable identity widget to prevent conflicts
identity:
  widget: false

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "What (Type)", name: "what", widget: "string", required: true, hint: "e.g. Museum, Housing, Cultural, etc." }
      - { label: "Who (Architect)", name: "who", widget: "string", required: true, hint: "e.g. Norman Foster, Zaha Hadid, etc." }
      - { label: "Where (Location)", name: "where", widget: "string", required: true, hint: "e.g. Berlin, Istanbul, Porto, etc." }
      - { label: "When (Year)", name: "when", widget: "string", required: true, hint: "e.g. 2022, 2023, 2024, etc." }
      - { label: "Images", name: "images", widget: "list", required: false, hint: "Add image paths" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "project.njk" }
