backend:
  name: github
  repo: alifiratuzun/abakus
  branch: main
  base_url: https://abakus-studio.netlify.app
  auth_endpoint: /.netlify/functions/auth
  display_url: https://abakus-studio.netlify.app
  auth_scope: repo
