backend:
  name: github
  repo: alifiratuzun/abakus
  branch: main
  base_url: https://abakus-studio.netlify.app
  auth_endpoint: api/auth

media_folder: "img"
public_folder: "/img"

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
